Vagrant.configure("2") do |config|
  config.vm.define "hailh13" do |hailh13|
    hailh13.vm.box = "ubuntu/trusty64"
    hailh13.vm.hostname = "hailh13"
    hailh13.vm.network "private_network", ip: "192.168.100.12"

    hailh13.vm.provider "virtualbox" do |vb|
      vb.name = "hailh13"
      vb.memory = "1024"
      vb.cpus = 2

      disk_path = File.expand_path("hailh13_extra_disk.vdi", File.dirname(__FILE__))

      
      unless File.exist?(disk_path)
        vb.customize ['createhd', '--filename', disk_path, '--size', 10240] 
      end

      
      vb.customize [
        'storageattach', :id,
        '--storagectl', 'SATAController',
        '--port', 1,
        '--device', 0,
        '--type', 'hdd',
        '--medium', disk_path
      ]
    end
  end
end

